### ISSUE TITLE
kubeVersion parsing is inconsistently handled

### ISSUE THREAD

**Issue by komish** [openshift-helm-charts/charts#1032]
Identified here: https://github.com/openshift-helm-charts/charts/pull/1031, logs below:

```
[INFO] Get modified charts. ../pr
[INFO] Query files : https://api.github.com/repos/openshift-helm-charts/charts/pulls/1031/files?per_page=100&page=1
[DEBUG] X-RateLimit-Limit : 5000
[DEBUG] X-RateLimit-Remaining  : 4993
[INFO] Verify user. Digitalpit, partners, sapiens, idit-runtime-umbrella-chart
[INFO] Check owners file against directory structure. partners, sapiens, idit-runtime-umbrella-chart
[INFO] Generate report info using chart-verifier on path : /home/runner/work/charts/charts/pr-branch/charts/partners/sapiens/idit-runtime-umbrella-chart/1.0.[18](https://github.com/openshift-helm-charts/charts/actions/runs/6000946221/job/16274094922#step:23:19)/report.yaml
[INFO] report annotations : {'charts.openshift.io/digest': 'sha256:4f454ed42420a2b89a4ff3c265415556c1c3bc244fe94522eefa295b33c0cc7b', 'charts.openshift.io/lastCertifiedTimestamp': '2023-08-28T12:44:39.471229+00:00', 'charts.openshift.io/testedOpenShiftVersion': '4.10', 'charts.openshift.io/supportedOpenShiftVersions': '4.10 - 4.13'}
[INFO] Generate report info using chart-verifier on path : /home/runner/work/charts/charts/pr-branch/charts/partners/sapiens/idit-runtime-umbrella-chart/1.0.18/report.yaml
[INFO] report chart : {'name': 'idit-runtime', 'version': '1.0.18', 'description': 'A Helm chart for Kubernetes', 'apiVersion': 'v2', 'appVersion': '1.16.0', 'annotations': {'app.idit/version': '[19](https://github.com/openshift-helm-charts/charts/actions/runs/6000946221/job/16274094922#step:23:20).2.0.2', 'charts.openshift.io/name': 'IDITSuite 18.'}, 'kubeVersion': '>= 1.[23](https://github.com/openshift-helm-charts/charts/actions/runs/6000946221/job/16274094922#step:23:24).0 <= 1.26.3', 'dependencies': [{'name': 'mono', 'version': '1.0.15', 'repository': 'https://harbor.idit.sapiens.com/chartrepo/core'}, {'name': 'apache-active-mq', 'version': '1.0.10', 'repository': 'https://harbor.idit.sapiens.com/chartrepo/infrastructure'}, {'name': 'sua', 'version': '1.0.7', 'repository': 'https://harbor.idit.sapiens.com/chartrepo/core', 'condition': 'sua.enabled'}, {'name': 'couchbase-setup', 'version': '1.0.5', 'repository': 'https://harbor.idit.sapiens.com/chartrepo/core', 'condition': 'sua.enabled'}], 'type': 'application'}
Value error with kubeVersion -  NpmSpec : >= 1.23.0 <= 1.[26](https://github.com/openshift-helm-charts/charts/actions/runs/6000946221/job/16274094922#step:23:27).3, see if it fixable
Fixed value error in kubeVersion : >=1.23.0----1.26.3
Error:  Submitted report is not valid: Kube Version >= 1.23.0 <= 1.26.3 -> >=4.10 does not match supportedOpenShiftVersions: 4.10 - 4.13
Submitted report is not valid: Kube Version >= 1.23.0 <= 1.26.3 -> >=4.10 does not match supportedOpenShiftVersions: 4.10 - 4.13
Error: Process completed with exit code 1.
```

The python semantic_version library that's we're using is seemingly less tolerant to arbitrary whitespace in the kubeVersion value that is submitted in a given Chart.yaml, and subsequently in a report.yaml. This results in the Kube to OCP version mapping to fail in our pipeline in some cases where random whitespace is sprinkled into the kubeVersion string, but seemingly function without issue in Chart Verifier (which leverages Mastermind Semver as far as I can see). 

Furthermore, when we try to utilize the `semantic_version.Version.coerce` method to parse the user's kubeVersion input, we're getting results we don't really want. 

---

Explaining the concrete example identifier in that log output. The partner provided:

```yaml
kubeversion: '>= 1.23.0 <= 1.26.3'
```

Note the whitespace before/after each numeric component. The following is what seems to be expected by the semantic_version py lib we use.

```yaml
# no whitespace separating range indications and the associated numerical values
kubeversion: '>=1.23.0 <=1.26.3'
```

^ This would work without issue.

However, what ends up happening is that semantic_version fails to parse the input `>= 1.23.0 <= 1.26.3` as a valid semantic version range. 

This is all happening in this block: https://github.com/openshift-helm-charts/charts/blob/main/scripts/src/report/verifier_report.py#L190-L224

More specifically here: https://github.com/openshift-helm-charts/charts/blob/main/scripts/src/report/verifier_report.py#L192C54-L192C63 - is where we try to grab the corresponding range representation for the kubeVersion we're getting.

When we try to parse the kubeVersion, we run into an error: https://github.com/openshift-helm-charts/charts/blob/main/scripts/src/chartrepomanager/indexannotations.py#L34

```python
>>> sv.Version('>= 1.23.0 <= 1.26.3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jogonza/code/go/src/github.com/openshift-helm-charts/development/scripts/myve/lib64/python3.11/site-packages/semantic_version/base.py", line 105, in __init__
    major, minor, patch, prerelease, build = self.parse(version_string, partial)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jogonza/code/go/src/github.com/openshift-helm-charts/development/scripts/myve/lib64/python3.11/site-packages/semantic_version/base.py", line 318, in parse
    raise ValueError('Invalid version string: %r' % version_string)
ValueError: Invalid version string: '>= 1.23.0 <= 1.26.3'
```

Currently, there is logic to try and clean up the input string a bit and then leverage `coerce` to try and get this parsed successfully... and it does parse but with the same intent. The existing logic manipulates the kubeVersion to produce `1.23.0 <= 1.26.3`  (https://github.com/openshift-helm-charts/charts/blob/main/scripts/src/chartrepomanager/indexannotations.py#L43C13-L52) which already doesn't have the same intent as the original kubeVersion. Once that's "coerced" into a Version, we get this:

```python
>>> sv.Version.coerce('1.23.0 <= 1.26.3')
Version('1.23.0----1.26.3')
```

This has a drastically different meaning. In effect, this is "1.23.0 and later". The latter constraint has been removed. 

The fallout from that is that we fall into our block that checks for open-endedness in our version range, which produces the result we saw in the original failure (`>=4.10.0`).

That's here: https://github.com/openshift-helm-charts/charts/blob/main/scripts/src/chartrepomanager/indexannotations.py#L80-L81.

---

In summary, we need to become a bit more consistent in how the pipeline and chart verifier interpret these strings. If we leverage two different tools, we need to ensure they produce the same outputs.

I could see any of the following being valid paths forward:

1) Collapse into a single tool to do interpreting in both cases. If the chart verifier tooling is more consistent, figure out how to use that here.
2) Identify a proper interpreting library to use in the pipeline. Perhaps NpmSpec isn't what we want to be using? This requires some digging into why NpmSpec is what was used to begin with. Maybe we need to look into using https://pypi.org/project/univers/ ?
3) Remove the massaging we do to try to improve the likelihood of successful coerscion, and just fail outright indicating the kubeVersion formatting is wrong. Enforce an opinion on what this format should look like. If need be, enforce this at the chart-verifier level as well.

**Comment by mgoerens** [comment]
In order to correctly parse the `kubeVersion` field in Python, we would need to craft our own library, re-implementing the logic described [in the helm docs](https://helm.sh/docs/topics/charts/#the-kubeversion-field). 

> For a detailed explanation of supported semver constraints see [Masterminds/semver](https://github.com/Masterminds/semver).

I would go with your first option: call an external go program (chart-verifier) in order to use Mastermind/semver.

A few additional findings / notes:

As you pointed out, we currently parse version ranges incorrectly. We seem to be expected ranges in the form of `1.20.0 - 1.23.0` (see https://github.com/openshift-helm-charts/charts/blob/main/scripts/src/chartrepomanager/indexannotations.py#L38).

Note that this is allowed by `NpmSpec` but not by `SimpleSpec`:
```
>>> sv.NpmSpec('1.1.0 - 1.19.0')
<NpmSpec: '1.1.0 - 1.19.0'>
>>> sv.SimpleSpec('1.1.0 - 1.19.0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mgoerens/dev/github.com/mgoerens/development/.direnv/python-3.9.17/lib/python3.9/site-packages/semantic_version/base.py", line 618, in __init__
    self.clause = self._parse_to_clause(expression)
  File "/home/mgoerens/dev/github.com/mgoerens/development/.direnv/python-3.9.17/lib/python3.9/site-packages/semantic_version/base.py", line 1014, in _parse_to_clause
    return cls.Parser.parse(expression)
  File "/home/mgoerens/dev/github.com/mgoerens/development/.direnv/python-3.9.17/lib/python3.9/site-packages/semantic_version/base.py", line 1034, in parse
    raise ValueError("Invalid simple block %r" % block)
ValueError: Invalid simple block '1.1.0 - 1.19.0'
```

I'm not exactly sure what corner case this is trying to solve: https://github.com/openshift-helm-charts/charts/blob/main/scripts/src/chartrepomanager/indexannotations.py#L44-L52

**Comment by komish** [comment]
> I'm not exactly sure what corner case this is trying to solve: https://github.com/openshift-helm-charts/charts/blob/main/scripts/src/chartrepomanager/indexannotations.py#L44-L52

100% agree. The corner case covered here is lacking in clarity, so to my eye, it should be removed and we should decide what to do here instead (e.g. fail with "this is invalid").

> I would go with your first option: call an external go program (chart-verifier) in order to use Mastermind/semver.

I agree with this approach. We can easily just run a task in GHA that's evaluating this value and wire up the evaluated value to determine if it's correct. I would love to not have to extract out a library component, build an action, etc. but this seems like the most straightforward option if there's no good way to parse these semantic version values consistently.

Maybe it makes sense to have it added into the `chart-verifier report` subcommand... although if we  are evaluating the Chart.yaml instead of reports, then maybe this doesn't make perfect sense.

**Comment by mgoerens** [comment]
This has been fixed by https://github.com/redhat-certification/chart-verifier/pull/408 and https://github.com/openshift-helm-charts/development/pull/264
