### ISSUE TITLE
Auto-merge is broken.  

### ISSUE THREAD

**Issue by mmulholla** [openshift-helm-charts/charts#119]
Auto merge is not working for pull requests.

**Comment by baijum** [comment]
Auto-merge was broken because of this commit: a340130348a440292af002cbf73b88e361345149

That commit replaced the bot account token with the GitHub actions account token. I would suggest reverting that commit for now. And we can address the concern about bot usage post GA.

@pedjak Let me know if you have any objection to the above suggestion.

cc. @jasperchui

**Comment by mmulholla** [comment]
From Predrag email:

In the last few weeks, we keep us busy with the discussion of whether
auto-merging on submitted PRs can be done without creating a dedicated
bot account. On the last Friday you raised the concern again:

https://github.com/openshift-helm-charts/charts/issues/119#issuecomment-834441061

I took some time today to better understand the problem and came with
the following repo:

https://github.com/openshift-helm-charts/sandbox

It demonstrates PR auto-merge without the dedicated bot, try to create
PR to see it in action. There is just a single workflow, but
containing several jobs. They all run within 'pull_request_target'.
Although it would be safer (and recommended) to run the verifier
without access to secrets, the trouble is that we do need to install
charts on the provisioned cluster, i.e. we need access to at least the
secret with the cluster token. However, we can run safe using the
approach taken by community-operator folks. If really needed, we can
add additional workflows that get triggered after PR workflow is
completed.

Just noticed an additional issue with the current set of workflows at
https://github.com/openshift-helm-charts/charts/ Namely, in "Release
Charts" workflow, chart-verifier is invoked one more time, fully
unneeded. The report obtained during verification should be used.

The single workflow proposed in sandbox can assure that, even without
the need to communicate via artifacts, simplifying things a lot. And
we can comment and label PR,  if needed.

**Comment by mmulholla** [comment]
Fixed
