### ISSUE TITLE
Interpret Chart Verifier report

### ISSUE THREAD

**Issue by jasperchui** [openshift-helm-charts/charts#12]
Interpret results from Chart Verifier 

Returns success if all mandatory checks pass
Returns warning if all mandatory checks pass and any optional checks fail
Returns fail if any mandatory checks fail

**Comment by isutton** [comment]
As I undertand then return codes should be implemented as follow:

-   `0` when all mandatory and optional checks pass;
-   `1` when any mandatory check fail; and
-   `-1` when all mandatory checks pass and any optional check fail.

**Comment by jasperchui** [comment]
Completed
