### ISSUE TITLE
Impacts of updating the existing released version of a Helm chart with the same version number

### ISSUE THREAD

**Issue by baijum** [openshift-helm-charts/charts#182]
A partner can not update the released version of a Helm chart with the same version number. This issue explains the impacts of updating the existing released version of a Helm chart with the same version number.

1.  When the Helm chart is getting published through the repository, it will reach the end-users immediately. And if a modified version publishes with the same version number, the end-user will not receive the changes. The version deployed on different environments (Dev, QA, Stage, Prod, etc.) will not be the same. It is going to make identifying issues very difficult.

2. Helm charts best practices document recommend using SemVer spec for versioning. Ref. https://helm.sh/docs/chart_best_practices/conventions/#version-numbers Version number increment for changes is a fundamental principle embraced by the SemVer spec.

3. It is nearly impossible to give security advisories without proper versioning of Helm chart releases.  If there is a Helm chart with different changesets, assigning a CVE entry would be difficult.

**Comment by baijum** [comment]
A related PR: #104 (Based on the discussion here, we can reopen it)

**Comment by dperaza4dustbit** [comment]
If no objections are raised I would fail on an attempt to change existing charts with a very clear message asking to re-submit

**Comment by mmulholla** [comment]
Would I workflow also fail as the chart tag and release would already exist?
