### ISSUE TITLE
scripts: format and style improvments proposal

### ISSUE THREAD

**Issue by zonggen** [openshift-helm-charts/charts#255]
* use a formatter like autopep8 to format code before submit changes
* use a logger like logging package and reduce use of print's
* single single quotes for string literals and use double quotes for error messages: https://docs.ckan.org/en/ckan-2.7.3/contributing/python.html#:~:text=Use single quotes,ve got an error!".
* docstring documentations on what each script is doing

**Comment by komish** [comment]
While I do thing this would be hugely beneficial, I'll close this for now as I think we may need to re-evaluate how much of the automation we run is executed using included libraries.
