### ISSUE TITLE
jenkins: need more information on chart support level

### ISSUE THREAD

**Issue by zonggen** [openshift-helm-charts/charts#311]
Currently there are three vendor types for charts: `partner`, `redhat` and `community`. Initially `jenkins` chart is moved under `redhat` vendor type: https://github.com/openshift-helm-charts/charts/tree/main/charts/redhat/redhat/jenkins but we want to confirm with the chart owner that this chart is not a community chart. Quote from Hugo Rivero when discussing about differences between `redhat` vs `community` charts:

> The main attribute for community are charts that are supported by a community and not covered by enterprise support. Community charts may come from Red Hatters, from partners (i.e. in their own upstream work). Charts that are in placed under Red Hat should be commercially supported, i.e. because they provide a supported installation method for a product or component.

If the chart is indeed a `community` chart, we'll move it from `charts/redhat/` to `charts/community/`, everything else remains and works the same.

cc @akram @waveywaves

**Comment by akram** [comment]
@zonggen I confirm you that this is commercially supported as this chart is used as an alternative to Jenkins openshift templates to install the Jenkins image for OpenShift, that we, Red Hat develop and support.
It could be used for community, but it is not its primary goal.

**Comment by zonggen** [comment]
Thanks @akram !
