### ISSUE TITLE
Add github link to https://charts.openshift.io/

### ISSUE THREAD

**Issue by strangiato** [openshift-helm-charts/charts#407]
From https://charts.openshift.io/ it isn't apparent that this is the GitHub repo that is the source of the charts in https://charts.openshift.io/.

It would be great to have a "Source" link pointing back to this repo in the readme that I would assume would update the charts URL.

**Comment by komish** [comment]
The https://charts.openshift.io/ index.html does link to this repository in the section title [OpenShift Certification Program](https://charts.openshift.io/#openshift-certification-program). As I'm not able to discern off-hand if this existed prior to this issue being created, I'm unable to assert that it's clear enough. That said, I do think it's clear that this repo backs that page, and so if that's not the case, please reopen!
