### ISSUE TITLE
What are the resource requirement limits of a chart under test?

### ISSUE THREAD

**Issue by bczoma** [openshift-helm-charts/charts#414]
I am trying to submit a chart for certification, our largest that creates an HA deployment of 3 Pods.

Each Pod's requirements are 2 cpus, 4025MiB of memory; in total 6 cpus and 12 GiB of memory.

I'm getting Error message(s): `timed out waiting for the condition`

I'm suspecting this is caused by not enough resources at the GH Action's OpenShift test cluster.

Can someone kindly confirm this? This is the PR: https://github.com/openshift-helm-charts/charts/pull/412

**Comment by bczoma** [comment]
A note that two our smaller (non-HA) charts with same logic have no issues, hence the thought it may be the resource requirements....

**Comment by komish** [comment]
Closing this as the referenced PR is merged.
