### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by jasperchui** [openshift-helm-charts/charts#48]
Update error message from github actions to include a direct link to where to get additional details.

**Comment by baijum** [comment]
* Link to the job failure page
* Include a summary of errors
* Username is not part of the OWNERS
* Pull request include non-chart related changes
* chart name and version should be the same in the directory structure, OWNERS file, Chart.yaml, report.yaml
* Digest mismatch message
* Ensure a sanity check on report  ensure these annotations: helm-chart.openshift.io/certifiedOpenShiftVersions, helm-chart.openshift.io/lastCertifiedTimestamp, helm-chart.openshift.io/digest
* [Martin] Ensure chart metadata is present in the report

**Comment by baijum** [comment]
PR #69

**Comment by baijum** [comment]
PR #77
