### ISSUE TITLE
charts/docs/readme.md info on changing OWNERS file is incomplete/wrong

### ISSUE THREAD

**Issue by jfrancin** [openshift-helm-charts/charts#512]
In the `/charts/docs/readme.md` file, at the very bottom, the section on "How to update the OWNERS file?" for partners points off to the new [Certification Guides](https://redhat-connect.gitbook.io/certification-guides/) page. If from there you then go into the [Partner Guide for OpenShift and Container Certification](https://redhat-connect.gitbook.io/partner-guide-for-red-hat-openshift-and-container/), and look through the section on Helm charts, there is only a scant mention about the fact that going through the process creates the OWNERS file, and _no mention whatsoever_ about how to change it/request that it be changed.

Since the OWNERS file's purpose has suffered feature creep (to add the `providerDelivery: True` keyword), there needs to be specific documentation on how to do this. Also, since Engineering has more control over this doc, the info should be here as well as in the published documentation.

**Comment by rocrisp** [comment]
This deems to be a good first issue but I can't assign it to myself.

**Comment by jfrancin** [comment]
You need to be added to the group that owns this GitHub repo.

**Comment by komish** [comment]
I believe this issue is resolved, so I'll mark it closed. If there's an action left, please feel to reopen this.
