### ISSUE TITLE
Installing the Nodejs helm chart 0.0.2 doesn't work on OpenShift (anymore?)

### ISSUE THREAD

**Issue by jerolimov** [openshift-helm-charts/charts#548]
The OpenShift Developer console supports importing Helm Chart samples from the `HelmChartRepository` https://charts.openshift.io

But when installing this HelmChart it creates a BuildConfig that reference an `ImageStreamTag` `nodejs:12`. But this `ImageStreamTag` doesn't exist on my clusters (tested this on 4.10 and 4.12):

```
➜  ~ oc get imagestreamtags.image.openshift.io -n openshift -o name | grep node | grep -v jenkins
imagestreamtag.image.openshift.io/nodejs:16-ubi9-minimal
imagestreamtag.image.openshift.io/nodejs:latest
imagestreamtag.image.openshift.io/nodejs:14-ubi7
imagestreamtag.image.openshift.io/nodejs:14-ubi8
imagestreamtag.image.openshift.io/nodejs:14-ubi8-minimal
imagestreamtag.image.openshift.io/nodejs:16-ubi8
imagestreamtag.image.openshift.io/nodejs:16-ubi8-minimal
imagestreamtag.image.openshift.io/nodejs:16-ubi9
```

Looks like the node.js version is referenced here: https://github.com/openshift-helm-charts/charts/blob/main/charts/redhat/redhat/nodejs/0.0.2/src/values.yaml#L46-L48

Maybe here as well? https://github.com/openshift-helm-charts/charts/blob/main/charts/redhat/redhat/nodejs/0.0.2/src/values.schema.json#L147-L151

I don't know why this IST is not part of our distribution anymore.

**Comment by dperaza4dustbit** [comment]
Still not understanding the issue, I'm able to install the NodeJs chart. Can you provide steps to reproduce?

**Comment by dperaza4dustbit** [comment]
nm, I see the BuildConfig Issue now @jerolimov . @isutton I think this is an easy fix moving to latest should do for now.

**Comment by isutton** [comment]
Instead of `latest`, I'd use the latest LTS NodeJS version with the latest supported UBI, in this case `14-ubi8-minimal`.

@dperaza4dustbit and @jerolimov, how do you feel about this?

**Comment by jerolimov** [comment]
Hey @isutton, I'm fine and recommend using an LTS version.

14 is already in Maintenance LTS mode, and 16 is the current Active LTS. But it's up to you. 😄

https://nodejs.org/en/about/releases/

**Comment by komish** [comment]
It's unclear if there are any remaining actions here. For now, I'll close this issue. Please feel free to re-open if there are any remaining tasks.
