### ISSUE TITLE
charts.openshift.io website should link this Git repository somewhere

### ISSUE THREAD

**Issue by jerolimov** [openshift-helm-charts/charts#549]
When researching an issue with a Helm Chart I quickly found the `HelmChartRepository` that refers https://charts.openshift.io

But the website doesn't contain any references where I can create a bug or research the existing bug reports, PR or source code.

It would be great if the website contains a reference https://github.com/openshift-helm-charts/charts or so.

**Comment by komish** [comment]
Closing as a duplicate of #407
