### ISSUE TITLE
Generate index.yaml entry from chart submission

### ISSUE THREAD

**Issue by jasperchui** [openshift-helm-charts/charts#6]
Generate index.yaml entry from chart submission
Include chart digest
Include human readable name #1

**Comment by isutton** [comment]
According to the epic, the entry should be added to the `index.yaml` file present in the `index` branch, and committed back to the repository; ultimately, updating the `index` branch should trigger the update of the repository hosted in <https://openshift-helm-charts.github.com/repo>.

**Comment by jasperchui** [comment]
Completed
