### ISSUE TITLE
Backend actions fail after submitting a PR

### ISSUE THREAD

**Issue by AbhishekBandarupalle** [openshift-helm-charts/charts#698]
https://github.com/openshift-helm-charts/charts/pull/697

I see the github action Chart Certification failed at PR content check. But do not see any logs to identify the reason for failure. The result is the same for multiple tries.
https://github.com/openshift-helm-charts/charts/pull/696
https://github.com/openshift-helm-charts/charts/pull/695

Need some help with this - this is a blocker for Partner's CNF certification

**Comment by komish** [comment]
@AbhishekBandarupalle I'm unsure if you still need assistance with this issue. Please send your PR again and we'll work though this there.
