### ISSUE TITLE
fortranix dsm-secrets-injector-chart is out of date.

### ISSUE THREAD

**Issue by mmulholla** [openshift-helm-charts/charts#706]
@manasag @frankus0512 

As part of some routine maintenance I noticed that the latest version (2.2-4.6) your helm chart dsm-secrets-injector-chart will no longer install on the latest version of OpenShift because the  kubeVersion in the chart is limited.

kubeVersion: '>= 1.16.0 < 1.22.0'

please submit a new chart if you want to work on later versions of OpenShift - latest is 4.12 on kubeVersion 1.25.

**Comment by komish** [comment]
@manasag @frankus0512 Please have a look when you've got a moment.
