### ISSUE TITLE
redis-sed references mongodb

### ISSUE THREAD

**Issue by komish** [openshift-helm-charts/charts#719]
the [redis-sed](https://github.com/openshift-helm-charts/charts/blob/main/charts/redhat/redhat/redis-sed/) chart makes references to mongodb in multiple places. I'm seeing:

values.schema.json:

```
...
  "properties": {
    "mongodb": {
      "type": "object",
      "required": [
        "sed"
      ],
...
```

README.md:

```
Therefore, the secret rendered by MongoDB SED Chart is a bindable service endpoint that can be projected to workloads using the Service
```

PTAL @fbm3307 (listed as [OWNER](https://github.com/openshift-helm-charts/charts/blob/main/charts/redhat/redhat/redis-sed/OWNERS#L6))

**Comment by komish** [comment]
Another quick ping for @fbm3307. I'll close this issue for now, please submit an updated chart to resolve this when you have a moment.

**Comment by fbm3307** [comment]
Okay will do
