### ISSUE TITLE
Fix issue with workflow that causes the bot to post a success message when failing in an unexpected place.

### ISSUE THREAD

**Issue by komish** [openshift-helm-charts/charts#785]
Ex. https://github.com/openshift-helm-charts/charts/pull/599#issuecomment-1516608443

**Comment by itroyano** [comment]
https://github.com/openshift-helm-charts/charts/blob/4301977deeded91f485f2d86a027c08c311eb19c/scripts/src/pullrequest/prepare_pr_comment.py#L127

Looks like the correct place. An additional else if could be required.

**Comment by komish** [comment]
Looks like that may be so. It may be worth refactoring so that we fallback to failure instead of fallback to success. Falling back to success feels like it has more consequences.

**Comment by komish** [comment]
This is resolved as of the pipeline 1.5.3 release. https://github.com/openshift-helm-charts/charts/pull/844
