### ISSUE TITLE
Accepted Helm chart new version does not show in catalog

### ISSUE THREAD

**Issue by bczoma** [openshift-helm-charts/charts#990]
PR: https://github.com/openshift-helm-charts/charts/pull/983
Chart: PubSub+ Event Broker for Developers

Submitted PR for version 3.3.2 and it has been merged to https://github.com/openshift-helm-charts/charts/tree/main/charts/partners/solace/pubsubplus-openshift-dev. However catalog still shows the older version 3.3.1.

At the same time other two charts I submitted correctly show the new version, 3.3.2.
See:
- PubSub+ Event Broker, HA (https://github.com/openshift-helm-charts/charts/tree/main/charts/partners/solace/pubsubplus-openshift-ha)
- PubSub+ Event Broker, non-HA (https://github.com/openshift-helm-charts/charts/tree/main/charts/partners/solace/pubsubplus-openshift)

Maybe automated propagation somehow failed for this one? Would it be possible to manually push in this case?
Thanks for any help!

**Comment by komish** [comment]
@bczoma will take a look.

**Comment by komish** [comment]
@bczoma this should be resolved. Our apologies for the inconvenience.

```
 ⤿ helm search repo  | grep openshift/solace
openshift/solace-pubsubplus-openshift          	3.3.2        	             	Deploy a single-node non-HA Solace PubSub+ Even...
openshift/solace-pubsubplus-openshift-dev      	3.3.2        	             	Deploy a minimum footprint single-node non-HA S...
openshift/solace-pubsubplus-openshift-ha       	3.3.2        	             	Deploy an HA redundancy group of Solace PubSub+...
```

If you have any further issues with this, reach out.

**Comment by bczoma** [comment]
@komish , thank you very much for the help!
